Repository aminnairi/discord-quizz-bot, pull requests merged in 2019-10, with the labels that each got.

#1 Leaderboard
  src/main.js
  src/question.js
  src/scores.js
Labels: enhancement

#2 Add env install command
  README.md
  makefile
Labels: documentation, enhancement

#3 Added code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#4 Added contributions guidelines
  CONTRIBUTING.md
Labels: documentation

#5 Added the MIT license
  LICENSE
Labels: documentation

#6 Added bot's commands documentation
  README.md
Labels: documentation

#9 Added some html questions
  src/questions.json
Labels: enhancement

#8 Sécurisation de la réinitialisation des scores
  src/main.js
Labels: enhancement

#7 Ajout d'une question sur php
  src/questions.json
Labels: enhancement

#11 Added some more PHP questions
  src/questions.json
Labels: enhancement

#15 Update questions.json
  src/questions.json
Labels: enhancement

#14 Update questions.json
  src/questions.json
Labels: enhancement

#20 Add javascript linting
  .eslintrc.js
  docker-compose.yaml
  docker/node/Dockerfile
  makefile
  package-lock.json
  package.json
  src/question.js
  src/scores.js
Labels: enhancement

#21 Added json linting
  .eslintrc.js
  package-lock.json
  package.json
Labels: enhancement

#22 Added Travis CI configuration
  .travis.yaml
Labels: enhancement

#23 Added rollup build configuration
  .gitignore
  .travis.yml
  CONTRIBUTING.md
  makefile
  package-lock.json
  package.json
  rollup.config.js
  src/questions.json
Labels: enhancement

#28 Added coveralls and shields
  .travis.yml
  README.md
  package-lock.json
  package.json
Labels: enhancement
